### ISSUE TITLE
Align Submit Button to center

### ISSUE THREAD

**Issue by vighneshmufc** [CLIxIndia-Dev/CLIxDashboard#16]
**Align Submit Button to center*
Align Submit Button to center in School Selection Menu

**Screenshots**
![Screenshot (368)](https://user-images.githubusercontent.com/14256897/103261816-d756aa00-49c8-11eb-84ed-b8e9298b04d6.png)

**Comment by yogeshu** [comment]
![Screenshot from 2020-12-29 16-21-11](https://user-images.githubusercontent.com/32289745/103278623-f3227600-49f1-11eb-910d-302aa2991ea5.png)

**Comment by vighneshmufc** [comment]
Working.Closed
