### ISSUE TITLE
Change Case in Title

### ISSUE THREAD

**Issue by vighneshmufc** [CLIxIndia-Dev/CLIxDashboard#22]
**Change Case in Title**
As a Test Engineer, I  want to see page title in proper case so that it follows design convention.

**To Reproduce**
1. Go to 'https://staging-clixdashboard.tiss.edu/home'
2. Scroll to Title Bar
3. See error

**Expected behavior**
Character Case Should be consistent
 CLIxDashboard - implementation metric and learning analytics
 CLIxDashboard - Implementation Metric and Learning Analytics  

**Screenshots**
![Screenshot (380)](https://user-images.githubusercontent.com/14256897/112924510-e6670880-912d-11eb-92d7-b9ef39ad5042.png)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [chrome]
 - Version [89.0]

**Additional context**

**Comment by yogeshu** [comment]
![Uploading Screenshot from 2021-03-30 13-53-38.png…]()

**Comment by vighneshmufc** [comment]
fixed
