### ISSUE TITLE
Submit Button Gap

### ISSUE THREAD

**Issue by vighneshmufc** [CLIxIndia-Dev/CLIxDashboard#24]
**Change Case in Title**
As a Test Engineer, I  want to see the gap between school and submit button design changed so that it changes the look and feel of website.

**To Reproduce**
1. Go to 'https://staging-clixdashboard.tiss.edu/home'
2. Scroll to Submit Button
3. See error

**Expected behavior**
There should be some gap between School tab and submit button .
**Screenshots**
![Screenshot (381)](https://user-images.githubusercontent.com/14256897/112925389-69d52980-912f-11eb-984c-94cf5680caca.png)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [chrome]
 - Version [89.0]

**Comment by yogeshu** [comment]
![Screenshot from 2021-03-30 13-49-33](https://user-images.githubusercontent.com/32289745/112957153-c996f900-915e-11eb-8f40-260124ad6355.png)
The button design is change - check @vighneshmufc

**Comment by vighneshmufc** [comment]
fixed
