### ISSUE TITLE
Add gaps in mobile view

### ISSUE THREAD

**Issue by vighneshmufc** [CLIxIndia-Dev/CLIxDashboard#25]
**Add gaps in mobile view**
As a Test Engineer, I  want to see the gaps between fields in mobile view so that it changes the look and feel of website.

**To Reproduce**
1. Go to 'https://staging-clixdashboard.tiss.edu/home' on mobile
2. Scroll to Submit Button
3. See error

**Expected behavior**
Add Proper gaps to change look and feel in mobile view
**Screenshots**
![166365230_584475682474161_8485352461093784803_n](https://user-images.githubusercontent.com/14256897/112927322-698a5d80-9132-11eb-96db-93447f5344de.png)

**Desktop (please complete the following information):**
 - OS: [Android 11]
 - Browser [chrome]
 - Version [89.0]

**Comment by yogeshu** [comment]
![Screenshot from 2021-03-30 13-50-32](https://user-images.githubusercontent.com/32289745/112957315-f0edc600-915e-11eb-94a1-5fcc79391c63.png)
- check @vighneshmufc

**Comment by yogeshu** [comment]
![Screenshot from 2021-03-30 13-52-24](https://user-images.githubusercontent.com/32289745/112957590-34e0cb00-915f-11eb-985b-c22dde3358a7.png)

**Comment by vighneshmufc** [comment]
add one gap between submit button and note

**Comment by vighneshmufc** [comment]
Fixed.
