### ISSUE TITLE
FAQ Question on Hover Color Change

### ISSUE THREAD

**Issue by vighneshmufc** [CLIxIndia-Dev/CLIxDashboard#29]
**FAQ Question on Hover Color Change**
As a Test Engineer, I want to see the colour on mouse hover to change so that it becomes readable.

**To Reproduce**
1. Go to 'https://staging-clixdashboard.tiss.edu'
2. Click on 'Documentation'
3. Scroll down to 'FAQs'

**Expected behavior**
Change colour on hover
**Screenshots**
![Screenshot (390)](https://user-images.githubusercontent.com/14256897/112954110-bafb1280-915b-11eb-8b09-193621230e40.png)

**Desktop (please complete the following information):**
 - OS: [Android 11]
 - Browser [chrome]
 - Version [89.0]

**Comment by yogeshu** [comment]
![Uploading Screenshot from 2021-03-30 13-54-57.png…]()

**Comment by vighneshmufc** [comment]
Color isnt changing now..it will be better to show a icon on side to suggest it is a dropdown

**Comment by vighneshmufc** [comment]
Closed.
