### ISSUE TITLE
3.1 Data Processing should be 3.2 Data Processing

### ISSUE THREAD

**Issue by vighneshmufc** [CLIxIndia-Dev/CLIxDashboard#34]
**FAQ Question on Hover Color Change**
As a Test Engineer, I want to see the item 3.1 Data Processing to 3.2 Data Processing to improve look and feel of the website
**To Reproduce**
1. Go to 'https://staging-clixdashboard.tiss.edu/documentation#getting-started'
2. Scroll on ''
3. See error

**Expected behavior**
It should be numbered properly
**Screenshots**
![image](https://user-images.githubusercontent.com/14256897/114971210-7f6d8180-9e99-11eb-9f82-9b2bd530ec8f.png)

**Desktop (please complete the following information):**
 - OS: [Android 11]
 - Browser [chrome]
 - Version [89.0]

**Comment by yogeshu** [comment]
Done

**Comment by vighneshmufc** [comment]
Closed.
