### ISSUE TITLE
Add a note to contact on the login page

### ISSUE THREAD

**Issue by SadaqatMulla** [CLIxIndia-Dev/CLIxDashboard#51]
**Is your feature request related to a problem? Please describe.**
If some school teacher dont have login ID or have forgotten then there should be information readily available upfront. Since we don't have **Forgot Password** or **Sign Up** we need a **Note**.

**Describe the solution you'd like**

**Describe alternatives you've considered**
Below the **Sign In** button place this text:
**Note:** Don't have login ID? Please write to us at contact@clix.tiss.edu

**Comment by VirajUtekar** [comment]
**Expectation:**
should display note on SIgn-In page as "Note: Don't have login ID? Please write to us at contact@clix.tiss.edu" as site doesn't have forgot password feature.

**Actual**
display note on SIgn-In page as "Note: Don't have login ID? Please write to us at contact@clix.tiss.edu"

**Status:**
This issue been resolved

**Screenshot:**
![Screenshot from 2021-12-24 22-34-14](https://user-images.githubusercontent.com/90617515/147366075-2178beb0-e5dc-4495-9fa1-495edb7c4dc5.png)

**Desktop:**
 OS:[Ubuntu 20.04.3]
 Browser:[Chrome]
 Version:[95]
