### ISSUE TITLE
Correct the spelling of Aizawl district

### ISSUE THREAD

**Issue by SadaqatMulla** [CLIxIndia-Dev/CLIxDashboard#52]
**Describe the bug**
On the home page, District selection/filter menu spelling of **Aizawl** district is appearing incorrectly as **Aizwal** (under Mizoram state).

**To Reproduce**
1. Go to 'Home page'
2. Select state as Mizoram
3. District dropdown menu will list **Aizwal**

**Expected behavior**
Spelling should be **Aizawl**

> RCA:
> The spelling was incorrect in the document [CLIxDashboard-Login-IDs](https://docs.google.com/spreadsheets/d/1-5Vwyaw_dDz4Mf4PBXkz0ZSsL0KhX1BXuATdElaeFc8/edit?usp=sharing) (use clixindia id to open)

**Comment by DurgaSwetha** [comment]
Required change done in the postgres database

**Comment by VirajUtekar** [comment]
**Expectation:**
The District list for Mizoram state should display Aizawl

**Actual**
The District list for Mizoram state display's Aizawl

**Status**
Pass

**Screenshot:**
![Screenshot from 2021-12-24 22-28-07](https://user-images.githubusercontent.com/90617515/147365824-cac5ede7-3788-495a-bca1-07d6847f9a3e.png)

**Desktop:**
  OS:[Ubuntu 20.04.3]
  Browser:[Chrome]
  Version:[95]
