### ISSUE TITLE
Spell Check on Landing Page #2

### ISSUE THREAD

**Issue by vighneshmufc** [CLIxIndia-Dev/CLIxDashboard#6]
**Spell Check on Landing Page 2**
In the landing page under Documentation, spelling in text (visualsations) need to be rectified.

**Comment by yogeshu** [comment]
![Uploading Screenshot from 2020-12-29 11-07-11.png…]()

**Comment by yogeshu** [comment]
I found no such error as it was fixed. please attached the ss of landing page

**Comment by vighneshmufc** [comment]
Fixed.
