### ISSUE TITLE
About Page Modifications

### ISSUE THREAD

**Issue by vighneshmufc** [CLIxIndia-Dev/CLIxDashboard#9]
**About Page Modifications**
In the About Section - An image should be added to the text in that particular orientation only which encompasses the overall CLIx Design.

**Screenshots**
![Screenshot (364)](https://user-images.githubusercontent.com/14256897/103260488-d5d6b300-49c3-11eb-84a0-54e2128bd1a2.png)

**Comment by vighneshmufc** [comment]
![Screenshot (365)](https://user-images.githubusercontent.com/14256897/103260508-e8e98300-49c3-11eb-9848-15bfd9adf25c.png)

Needs some more work. Alignment etc. @yogeshu

**Comment by yogeshu** [comment]
The Image we are using is a placeholder for a real image need to be provided. @vighneshmufc

**Comment by vighneshmufc** [comment]
Task will remain open till then

**Comment by vighneshmufc** [comment]
Closed.
